/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author mateo
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        BtgrpSeleccion = new javax.swing.ButtonGroup();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        lblBienvenido = new javax.swing.JLabel();
        JrbtnEmpleado = new javax.swing.JRadioButton();
        JrbtnCliente = new javax.swing.JRadioButton();
        lblCedula = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        JpasswordContrasena = new javax.swing.JPasswordField();
        BtnIngresar = new javax.swing.JButton();
        lblPregunta = new javax.swing.JLabel();
        JrbtnAdministrador = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JmtGestionarCliente = new javax.swing.JMenuItem();
        JmtGestionarEmpleado = new javax.swing.JMenuItem();
        JmtSalir = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBienvenido.setText("BIENVENIDO");

        BtgrpSeleccion.add(JrbtnEmpleado);
        JrbtnEmpleado.setText("Empleado");
        JrbtnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JrbtnEmpleadoActionPerformed(evt);
            }
        });

        BtgrpSeleccion.add(JrbtnCliente);
        JrbtnCliente.setText("Cliente");
        JrbtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JrbtnClienteActionPerformed(evt);
            }
        });

        lblCedula.setText("Cedula");

        lblPassword.setText("Password");

        txtCedula.setEnabled(false);

        JpasswordContrasena.setEnabled(false);

        BtnIngresar.setText("Ingresar");
        BtnIngresar.setEnabled(false);

        lblPregunta.setText("Desea ingresar a :");

        BtgrpSeleccion.add(JrbtnAdministrador);
        JrbtnAdministrador.setText("Administrador");
        JrbtnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JrbtnAdministradorActionPerformed(evt);
            }
        });

        jMenu1.setText("Gestionar");

        JmtGestionarCliente.setText("Gestionar Cliente");
        jMenu1.add(JmtGestionarCliente);

        JmtGestionarEmpleado.setText("Gestionar Empleado");
        JmtGestionarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmtGestionarEmpleadoActionPerformed(evt);
            }
        });
        jMenu1.add(JmtGestionarEmpleado);

        JmtSalir.setText("Salir");
        JmtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmtSalirActionPerformed(evt);
            }
        });
        jMenu1.add(JmtSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBienvenido)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPregunta)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JrbtnEmpleado)
                                    .addComponent(JrbtnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JrbtnAdministrador))))
                        .addGap(0, 125, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPassword)
                                .addGap(27, 27, 27)
                                .addComponent(JpasswordContrasena))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCedula)
                                .addGap(44, 44, 44)
                                .addComponent(txtCedula)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(BtnIngresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(JrbtnEmpleado)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPregunta)
                    .addComponent(JrbtnCliente))
                .addGap(4, 4, 4)
                .addComponent(JrbtnAdministrador)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(JpasswordContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnIngresar)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JrbtnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JrbtnEmpleadoActionPerformed
        BtnIngresar.setEnabled(true);
        txtCedula.setEnabled(true);
        JpasswordContrasena.setEnabled(true);
        limpiar();


    }//GEN-LAST:event_JrbtnEmpleadoActionPerformed

    private void JmtGestionarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmtGestionarEmpleadoActionPerformed

    }//GEN-LAST:event_JmtGestionarEmpleadoActionPerformed

    private void JmtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmtSalirActionPerformed
        dispose();
    }//GEN-LAST:event_JmtSalirActionPerformed

    private void JrbtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JrbtnClienteActionPerformed
        BtnIngresar.setEnabled(true);
        txtCedula.setEnabled(true);
        JpasswordContrasena.setEnabled(true);
        limpiar();
    }//GEN-LAST:event_JrbtnClienteActionPerformed

    private void JrbtnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JrbtnAdministradorActionPerformed
        BtnIngresar.setEnabled(true);
        txtCedula.setEnabled(true);
        JpasswordContrasena.setEnabled(true);
        limpiar();
    }//GEN-LAST:event_JrbtnAdministradorActionPerformed
    public void limpiar() {
        txtCedula.setText("");
        JpasswordContrasena.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtgrpSeleccion;
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JMenuItem JmtGestionarCliente;
    private javax.swing.JMenuItem JmtGestionarEmpleado;
    private javax.swing.JMenuItem JmtSalir;
    private javax.swing.JPasswordField JpasswordContrasena;
    private javax.swing.JRadioButton JrbtnAdministrador;
    private javax.swing.JRadioButton JrbtnCliente;
    private javax.swing.JRadioButton JrbtnEmpleado;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
