/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtCliente;
import Controlador.CtEmpleado;
import Controlador.CtLogin;
import Modelo.ClsAdministrador;
import Modelo.ClsCliente;
import Modelo.ClsEmpleado;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author mateo
 */
public class FrmLogin extends javax.swing.JFrame {

    ClsAdministrador administrado;
    ArrayList<ClsEmpleado> listaEmpleado;
    ArrayList<ClsCliente> listaCliente;
    CtEmpleado controladorEmpleado;
    CtCliente controladorCliente;
    CtLogin controladorLogin;

    public FrmLogin() {
        initComponents();
        controladorEmpleado = new CtEmpleado();
        controladorLogin = new CtLogin();
        controladorCliente=new CtCliente();
        administrado = new ClsAdministrador();
        listaCliente=new ArrayList<ClsCliente>();
        listaEmpleado=new ArrayList<ClsEmpleado>();
        try {
            listaEmpleado = controladorEmpleado.cargarArchivo(listaEmpleado);
            listaCliente=controladorCliente.cargarArchivo(listaCliente);
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        BtgrpSeleccion = new javax.swing.ButtonGroup();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        JrbtnEmpleado = new javax.swing.JRadioButton();
        JrbtnCliente = new javax.swing.JRadioButton();
        lblCedula = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        JpasswordContrasena = new javax.swing.JPasswordField();
        BtnIngresar = new javax.swing.JButton();
        lblPregunta = new javax.swing.JLabel();
        JrbtnAdministrador = new javax.swing.JRadioButton();
        lblBienvenido = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JmGestionar = new javax.swing.JMenu();
        JmtGestionarCliente = new javax.swing.JMenuItem();
        JmOpciones = new javax.swing.JMenu();
        JtmSalir = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\ProyectosJava\\proyectolenguaje\\src\\Images\\background-1205309_960_720.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtgrpSeleccion.add(JrbtnEmpleado);
        JrbtnEmpleado.setText("Empleado");
        JrbtnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JrbtnEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(JrbtnEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 70, -1, -1));

        BtgrpSeleccion.add(JrbtnCliente);
        JrbtnCliente.setText("Cliente");
        JrbtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JrbtnClienteActionPerformed(evt);
            }
        });
        getContentPane().add(JrbtnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 100, 78, -1));

        lblCedula.setText("Cedula");
        getContentPane().add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 170, -1, -1));

        lblPassword.setText("Password");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 207, -1, -1));

        txtCedula.setEnabled(false);
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 168, 229, -1));

        JpasswordContrasena.setEnabled(false);
        getContentPane().add(JpasswordContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 205, 229, -1));

        BtnIngresar.setIcon(new javax.swing.ImageIcon("D:\\ProyectosJava\\proyectolenguaje\\src\\Images\\iconfinder_Login_73221 (3).png")); // NOI18N
        BtnIngresar.setText("Ingresar");
        BtnIngresar.setBorder(null);
        BtnIngresar.setBorderPainted(false);
        BtnIngresar.setContentAreaFilled(false);
        BtnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnIngresar.setEnabled(false);
        BtnIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnIngresar.setIconTextGap(-3);
        BtnIngresar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnIngresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 140, -1));

        lblPregunta.setBackground(new java.awt.Color(255, 255, 255));
        lblPregunta.setText("Desea ingresar a :");
        getContentPane().add(lblPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 104, -1, -1));

        BtgrpSeleccion.add(JrbtnAdministrador);
        JrbtnAdministrador.setText("Administrador");
        JrbtnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JrbtnAdministradorActionPerformed(evt);
            }
        });
        getContentPane().add(JrbtnAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 127, -1, -1));

        lblBienvenido.setText("BIENVENIDO");
        getContentPane().add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 12, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\ProyectosJava\\proyectolenguaje\\src\\Images\\iconfinder_Gnome-Application-Exit-64_55530.png")); // NOI18N
        jButton1.setText("Salir");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 100, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\ProyectosJava\\proyectolenguaje\\src\\Images\\depositphotos_188557138-stock-video-liquid-texture-form-lines-isolated.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -15, 440, 370));

        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        JmGestionar.setText("Registro");

        JmtGestionarCliente.setText("Cliente");
        JmtGestionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmtGestionarClienteActionPerformed(evt);
            }
        });
        JmGestionar.add(JmtGestionarCliente);

        jMenuBar1.add(JmGestionar);

        JmOpciones.setText("Opciones");

        JtmSalir.setText("Salir");
        JtmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtmSalirActionPerformed(evt);
            }
        });
        JmOpciones.add(JtmSalir);

        jMenuBar1.add(JmOpciones);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JrbtnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JrbtnEmpleadoActionPerformed
        BtnIngresar.setEnabled(true);
        txtCedula.setEnabled(true);
        JpasswordContrasena.setEnabled(true);
        limpiar();


    }//GEN-LAST:event_JrbtnEmpleadoActionPerformed

    private void JrbtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JrbtnClienteActionPerformed
        BtnIngresar.setEnabled(true);
        txtCedula.setEnabled(true);
        JpasswordContrasena.setEnabled(true);
        limpiar();
    }//GEN-LAST:event_JrbtnClienteActionPerformed

    private void JrbtnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JrbtnAdministradorActionPerformed
        BtnIngresar.setEnabled(true);
        txtCedula.setEnabled(true);
        JpasswordContrasena.setEnabled(true);
        limpiar();
    }//GEN-LAST:event_JrbtnAdministradorActionPerformed

    private void JtmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtmSalirActionPerformed
        dispose();
    }//GEN-LAST:event_JtmSalirActionPerformed

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed

        if (JrbtnEmpleado.isSelected() == true) {
            String cedula = txtCedula.getText();
            String password = JpasswordContrasena.getText();
            String empleado = JrbtnEmpleado.getText();
            String respuesta = controladorLogin.Login(listaEmpleado, listaCliente, administrado, empleado, cedula, password);
            if (respuesta.equals("Si")) {
                FrmmenuEmpleado menuempleado = new FrmmenuEmpleado();
                menuempleado.setVisible(true);
                dispose();
            } else {
                if (respuesta.equals("No")) {
                    JOptionPane.showMessageDialog(null, "cedula o password incorrecto");
                    limpiar();
                }
            }
        }
        if (JrbtnCliente.isSelected() == true) {
            String cedula = txtCedula.getText();
            String password = JpasswordContrasena.getText();
            String cliente = JrbtnCliente.getText();
            String respuesta = controladorLogin.Login(listaEmpleado, listaCliente, administrado, cliente, cedula, password);
            if (respuesta.equals("Si")) {
                FrmmenuCliente menucliente = new FrmmenuCliente();
                menucliente.setVisible(true);
                dispose();
            } else {
                if (respuesta.equals("No")) {
                    JOptionPane.showMessageDialog(null, "cedula o password incorrecto");
                    limpiar();
                }
            }

        }
        if (JrbtnAdministrador.isSelected() == true) {
            String cedula = txtCedula.getText();
            String password = JpasswordContrasena.getText();
            String administrador = JrbtnAdministrador.getText();
            String respuesta = controladorLogin.Login(listaEmpleado, listaCliente, administrado, administrador, cedula, password);
            if (respuesta.equals("Si")) {
                FrmAdministrador administradores = new FrmAdministrador();
                administradores.setVisible(true);
                dispose();
            } else {
                if (respuesta.equals("No")) {
                    JOptionPane.showMessageDialog(null, "cedula o password incorrecto");
                    limpiar();
                }
            }

        }
    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void JmtGestionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmtGestionarClienteActionPerformed
        FrmregistrarCliente registrocliente = new FrmregistrarCliente();
        registrocliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_JmtGestionarClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        System.exit(WIDTH);
    }//GEN-LAST:event_jButton1ActionPerformed
    public void limpiar() {
        txtCedula.setText("");
        JpasswordContrasena.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtgrpSeleccion;
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JMenu JmGestionar;
    private javax.swing.JMenu JmOpciones;
    private javax.swing.JMenuItem JmtGestionarCliente;
    private javax.swing.JPasswordField JpasswordContrasena;
    private javax.swing.JRadioButton JrbtnAdministrador;
    private javax.swing.JRadioButton JrbtnCliente;
    private javax.swing.JRadioButton JrbtnEmpleado;
    private javax.swing.JMenuItem JtmSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
